apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DEMO-MyHome
  annotations:
    github.com/project-slug: swimmio/DEMO-MyHome
    backstage.io/techdocs-ref: ./.swm
spec:
  type: other
  lifecycle: unknown
  owner: r-d
